# Generated by Django 2.2.4 on 2020-04-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_prediction_daten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='daten',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
