# Generated by Django 2.2.4 on 2020-04-28 21:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20200429_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='daten',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
